name: app build and deploy on k8s
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # This enables the manual "Run workflow" button
jobs:
  Build-app-DB:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required for OIDC
      contents: read    # Required for Checkout
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: image creation and push to ecr
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPO: abhishek-ecr/abhishek-ecr
          TAG: v1.0.${{ github.run_number }}
        
        run: |
          cd database-manager
          chmod +x build-image-kubernetes.sh
          ./build-image-kubernetes.sh
          cd ../database-sql
          chmod +x build-image-kubernetes.sh
          ./build-image-kubernetes.sh
          docker image list
          kubectl apply -f ../python-app-deployment.yaml
          kubectl apply -f ../python-app-service.yaml
          kubectl apply -f ../mysql-deployment.yaml
          kubectl apply -f ../mysql-service.yaml
          kubectl apply -f ../mysql-secret%20model.yaml
          kubectl apply -f ../python-app-secret.yaml
          #docker pull 702175642104.dkr.ecr.us-east-1.amazonaws.com/abhishek-ecr/abhishek-ecr:Terraform_golden_image_v1.0.16




  