name: app build and deploy on k8s
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # This enables the manual "Run workflow" button
jobs:
  buildecr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: image creation and push to ecr
        run: |
          cd database-manager
          chmod +x build-image-kubernetes.sh
          ./build-image-kubernetes.sh
          cd ../database-sql
          chmod +x build-image-kubernetes.sh
          ./build-image-kubernetes.sh
          docker image list

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


  